---
- name: Basculer la machine en Debian unstable
  hosts: localhost
  become: yes
  gather_facts: yes

  tasks:
    - name: Passer en unstable
      include_tasks: roles/packages/tasks/unstable.yml

