
---
- name: Remplace .zshrc file
  copy:
    src: .zshrc
    dest: "{{ ansible_env.HOME }}/.zshrc"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: '0644'
    backup: yes 
