
---
- name: Remplacer le fichier .zshrc de l'utilisateur
  copy:
    src: .zshrc
    dest: "{{ ansible_env.HOME }}/.zshrc"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: '0644'
    backup: yes  # fait une sauvegarde du fichier existant
